name: Hello World Workflow

on:
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # Runs on pull requests to the main branch

jobs:
  hello-world:
    runs-on: ubuntu-latest  # Defines the runner's OS

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Hello World Step
        run: echo "Hello, World!"
